export const samplePlayerData = [
  {
    id: 12486,
    tag: "image",
    url: "https://skoop-signage-storage-v2-staging.s3.amazonaws.com/x-_thqOCPSScjqmPZssrC88FoxX6Gp7jvMVKPn6ZZeA=_skoop_media_52582f9df3902ef1552b0d010012532a_597234540.png",
    duration: 10000,
    entryType: "skoop",
    ad_integration: {
      id: 0,
      integration_name: "",
      url: "",
      Params: null,
    },
    position: 1,
    scheduled_criteria: "",
  },
  {
    id: 12609,
    tag: "video",
    url: "https://skoop-signage-storage-v2-staging.s3.amazonaws.com/1jOau1fag3XtKMAv0sXgjU8IWtfgQLALp-55HwtHayw=_skoop_media_bea768a00e2ca5b15f2d8451795c0c7e_278745643.mp4",
    duration: 70000,
    entryType: "skoop",
    ad_integration: {
      id: 0,
      integration_name: "",
      url: "",
      Params: null,
    },
    position: 2,
    scheduled_criteria: "",
  },
  {
    id: 12657,
    tag: "iframe",
    url: "https://extension-apps.staging.skoopsignage.dev?appId=2&posId=3&entryId=1574&isLegacy=false&apiBaseUrl=backend-extension-v2.staging.skoopsignage.dev",
    duration: 30000,
    entryType: "skoop",
    ad_integration: {
      id: 0,
      integration_name: "",
      url: "",
      Params: null,
    },
    position: 3,
    scheduled_criteria: "",
  },
  {
    id: 0,
    tag: "vengo",
    url: "",
    duration: 10000,
    entryType: "vengo",
    ad_integration: {
      id: 60,
      integration_name: "vengo",
      url: "https://4ogiwi4hsj.execute-api.us-east-1.amazonaws.com/default/vengo-sync",
      Params: [
        {
          key: "organization_id",
          value: "signage_co",
        },
        {
          key: "ad_unit_id",
          value: "sc-000001",
        },
      ],
    },
    position: 4,
    scheduled_criteria: "",
  },
];
